### ISSUE TITLE
change default meta-data 

### ISSUE THREAD

**Issue by josephshepin** [TeeWallz/monty_balboa#1]
Hi, I went to share this website and unfortunately, the default react metadata text was displayed. To improve shareability of the site, I think you might want to change that. Thanks
![image](https://user-images.githubusercontent.com/31457361/140669848-a5a52566-3a83-4821-9498-419822658410.png)

**Comment by TeeWallz** [comment]
Thanks for the heads up @jshepin , I've pushed this through to prod

Apologies for my late reply, I really do appreciate it :)
